Auto 1688 - FaktoryWorker Batch extension
pepsico-ecommerce/faktory_worker pull request #1
Opened 2020-11-03 16:19 UTC by killahwave

2020-11-03 20:48 UTC, DavidAntaramian requested changes
Nice work. I've got a few inline comments

I think it would be easier if `build_batch_new_payload/4` was `build_batch_new_payload/2` and the second argument is a keyword list accepting something like `[on_complete: {mod, args, opts}, on_success: {mod, args, opts}, parent_id: bid]`. I realize this doesn't allow function heads, but I think it makes it easier to reason about.

2020-11-03 20:48 UTC, DavidAntaramian commented on lib/faktory_worker/batch.ex
> +        {complete_job, complete_options, complete_worker_module} = _complete
I'd flip this to have the module first

2020-11-03 20:48 UTC, DavidAntaramian commented on lib/faktory_worker/batch.ex
> +        {complete_job, complete_options, complete_worker_module} = _complete
I'd flip this to have the module first

2020-11-03 20:48 UTC, DavidAntaramian commented on lib/faktory_worker/batch.ex
> +        {success_job, success_options, success_worker_module} = _success,
I'd flip this to have the module first

2020-11-03 20:48 UTC, DavidAntaramian commented on lib/faktory_worker/batch.ex
> +  end
I don't think this is needed anymore

2020-11-03 20:48 UTC, DavidAntaramian commented on lib/faktory_worker/batch.ex
> +  end
I think it would be best to refactor the reading of `:faktory_name` into the `send_command/2` function; I also think that the default should be `FaktoryWorker`. I think

2020-11-04 20:11 UTC, killahwave commented
> [on_complete: {mod, args, opts}, on_success: {mod, args, opts}, parent_id: bid]

Should this be documented in the comments?

2020-11-11 21:20 UTC, DavidAntaramian requested changes
Sorry I took so long to get back to this 😦 

This is looking good. My remaining comments are about function design and maintainability.

As for your question:

> > [on_complete: {mod, args, opts}, on_success: {mod, args, opts}, parent_id: bid]
> 
> Should this be documented in the comments?

Yes, I think it should.

2020-11-11 21:20 UTC, DavidAntaramian commented on lib/faktory_worker/batch.ex
> +  end
I'd recommend compacting the logic here by using some private helper functions rather than having additional function heads on the public `build_batch_new_payload` function, especially because the last 3 function heads do a lot of the same thing.

I think in the `build_batch_new_payload/2` function definition you could have something like:

```
new_payload
|> maybe_put_parent_id(parent_id)
|> maybe_put_callback(:success, success)
|> maybe_put_callback(:complete, complete)
|> validate() # returns {:ok, payload} or {:error, reason}
```

The `maybe_` functions would no-op if the property to put was `nil`, and transform a `{module, job, options}` tuple for the callback definition into a job payload using `Job.build_payload/3`.

And then `validate/1` would ensure the payload has either a success or complete callback.

2020-11-11 21:20 UTC, DavidAntaramian commented on lib/faktory_worker/batch.ex
> +  end
I think the arguments for `open/2` and `commit/2` should be `bid` instead of `payload`.

2020-11-11 21:20 UTC, DavidAntaramian commented on lib/faktory_worker/batch.ex
> +  def build_batch_new_payload(
2¢ here: could probably just be `build_payload` for brevity, since the module already tells us it's a batch

2020-11-13 19:38 UTC, killahwave commented on lib/faktory_worker/batch.ex
> +  end
I was under the impression that bid stands for batchId. Perhaps I misunderstood but might be confusing to refer to the entire payload as bid. I will make the change either way.

2020-11-16 17:28 UTC, DavidAntaramian commented on lib/faktory_worker/batch.ex
> +  end
You're correct that `bid` stands for the batch ID. My recommendation is because when opening an existing batch or committing a batch, the only argument on the protocol is the `bid`—put differently, the `bid` _is_ the payload. I think it makes it clearer to the developer using the library.

2020-11-16 17:31 UTC, DavidAntaramian approved these changes
This looks awesome!!!!!

![](https://media.giphy.com/media/Hw8vYF4DNRCKY/giphy.gif)

2020-11-17 22:16 UTC, merged